version: "3.9"
services:
  web:
    container_name: 'blog'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
  postgredb:
    container_name: postgredb
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432

networks:
  default:
    name: postgre-service_default