apiVersion: v1
kind: Pod
metadata:
  name: blog
spec:
  containers:
  - name: app-blog-container
    image: docker.alekseikromski.com/blog:k8s
    ports:
    - containerPort: 3000
  imagePullSecrets:
  - name: regcred
