apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
  # Service name
  name: blog-services
spec:
  selector:
    # Selector for Pods
    app: blog-pods
  ports:
    # Port Map
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer