basePath: /api/v1
definitions:
  storage.Post:
    properties:
      ID:
        type: integer
      description:
        type: string
      title:
        type: string
    type: object
host: localhost:3001
info:
  contact: {}
  description: This is a simple api for aleksei kromski blog
  title: Swagger Aleksei Kromski blog API
  version: "1.0"
paths:
  /v1/create-post:
    post:
      description: Create a post
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create post
  /v1/get-last-posts:
    get:
      description: Get last posts from storage
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/storage.Post'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: List of last posts
swagger: "2.0"
